##Resgistrar
PUT http://localhost:3000/personas/123456789 HTTP/1.1
Content-Type: application/json

{
  "documento": "123123123",
  "tipoDocumento": "DNI",
  "primerNombre": "Juana",
  "primerApellido": "Pérez",
  "telefono": "123456789",
  "sexo": "Masculino",
  "correo": "juan@example.com",
  "foto": "https://example.com/foto.jpg"
}
